name = "OldEntryRegistry"
uuid = "9423fdf7-08bd-40ae-8ef9-e4a48bc76b94"
repo = "https://github.com/ven-k/OldEntryRegistry"
description = "MWE for old entries problem"

[packages]
961ee093-0014-501f-94e3-6117800e7a78 = { name = "ModelingToolkit", path = "M/ModelingToolkit" }
